stages:
  - build_and_test
  - deploy

variables:
  test_file_remote: /tmp/test_job_remote.txt
  test_file: /tmp/test_job.txt
  git_file: /tmp/test/test.txt 

test_job_ci:
  stage:  build_and_test
  tags:
    - test
    - api
  script:
    - echo "Project dir - "$CI_PROJECT_DIR > $test_file
    - echo "Project name - "$CI_PROJECT_NAME >> $test_file
    - test $git_file 
    - cat $git_file >> $test_file
    - ssh gitlab-runner@127.0.0.1 cat $test_file > $test_file_remote

test_job_cd:
  stage:  deploy
  tags:
    - api
  script:
    - if [ -e $test_file_remote ]; then cat $test_file_remote; else echo "Where my file?!" > $test_file_remote; fi
    - mkdir build
    - cp $test_file_remote build/
  artifacts:
      paths:
        - build/
