image: mcr.microsoft.com/dotnet/sdk:latest

stages:
  - unit
  - integration
  - e2e

unit tests:
  tags:
    - linux
  script:
    - python -m unittest Tests/UnitTests/GuideUnitTest.py
    - python -m unittest Tests/UnitTests/GuideServiceUnitTest.py
  stage: unit

integration tests:
  tags:
    - linux
  script:
    - python -m unittest Tests/IntTests/integration_tests.py
    - python -m unittest Tests/IntTests/integration_tests_mock.py
  stage: integration

e2e tests:
  tags: 
    - linux
  script:
    - python -m unittest Tests/E2E/testAll.py
  stage:
    e2e
