image: python:latest

unit-test:
    stage: test
    tags:
        - docker
    script:
        - python3 test_gaussian_sum_formula.py

doku:
    stage: deploy
    tags:
        - docker
    script:


lint-test:
    stage: test
    tags:
        - docker
    script:
