image: python:3.10.8-alpine3.17

stages:
  - unit
  - integration
  - e2e

unit tests:
  script:
    - pip3 install peewee
    - pip3 install pytest
    - pip3 install allure-pytest
    - python3 -m pytest Tests/UnitTests/GuideServiceUnitTest.py
    - python3 -m pytest Tests/UnitTests/GuideUnitTest.py
  stage: unit

integration tests:
  script:
    - pip3 install peewee
    - pip3 install pytest
    - pip3 install allure-pytest
    - python3 -m pytest Tests/IntTests/integration_tests.py
    - python3 -m pytest Tests/IntTests/integration_tests_mock.py
  stage: integration

e2e tests:
  script:
    - pip3 install peewee
    - pip3 install pytest
    - pip3 install allure-pytest
    - python3 -m pytest Tests/E2E/testAll.py
  stage: e2e