image: python:3.10.8-alpine3.17

stages:
  - unit

unit tests:
  script:
    - pip3 install peewee
    - python3 -m coverage run -m unittest Tests/UnitTests/GuideServiceUnitTest.py
    - python3 -m coverage run -m unittest Tests/UnitTests/GuideUnitTest.py
    - python3 -m coverage report
    - python3 -m coverage html
  stage: unit