image: python:3.10.8-alpine3.17

stages:
  - unit

unit tests:
  script:
    - pip3 install -r requirements.txt
    - python3 -m pytest Tests/UnitTests/GuideServiceUnitTest.py --alluredir=allure-results
    - python3 -m pytest Tests/UnitTests/GuideUnitTest.py --alluredir=allure-results
    - python3 -m allure serve allure-results
  stage: unit